add_library(DataPublicationActor SHARED DataPublicationActor.cpp)
target_include_directories(DataPublicationActor PUBLIC ..)
target_compile_definitions(DataPublicationActor PUBLIC "BOOST_TEST_DYN_LINK=1")
target_link_libraries(DataPublicationActor DataPublicationSession)
target_compile_definitions(DataPublicationActor PUBLIC VERBOSE)

add_subdirectory(test)